name: when push or pull_request master , auto release github page
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # リリース用に.gitignoreからdistを削除
      - name: Not ignore dist
        run: sed -i '/dist*/d' .gitignore
      # npmをキャッシュしてくれるやつ
      - name: yarn cache
        uses: bahmutov/npm-install@v1
      - name: Install and Build 🔧
        run: yarn build
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
